### ISSUE TITLE
audioop not found

### ISSUE THREAD

**Issue by tetrdd** [Echoshard/Gemini_Discordbot#17]
```
C:\GeminiDiscord\Gemini_Discordbot\geminidiscordbot.py:299: SyntaxWarning: invalid escape sequence '\.'
  '(youtube|youtu|youtube-nocookie)\.(com|be)/'
C:\GeminiDiscord\Gemini_Discordbot\geminidiscordbot.py:300: SyntaxWarning: invalid escape sequence '\?'
  '(watch\?v=|embed/|v/|.+\?v=)?([^&=%\?]{11})'
Traceback (most recent call last):
  File "C:\GeminiDiscord\Gemini_Discordbot\geminidiscordbot.py", line 1, in <module>
    import discord
  File "C:\Users\eddis\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\__init__.py", line 23, in <module>
    from .client import *
  File "C:\Users\eddis\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\client.py", line 51, in <module>
    from .sku import SKU, Entitlement
  File "C:\Users\eddis\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\sku.py", line 31, in <module>
    from .app_commands import MissingApplicationID
  File "C:\Users\eddis\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\app_commands\__init__.py", line 12, in <module>
    from .commands import *
  File "C:\Users\eddis\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\app_commands\commands.py", line 53, in <module>
    from .models import Choice
  File "C:\Users\eddis\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\app_commands\models.py", line 44, in <module>
    from ..member import Member
  File "C:\Users\eddis\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\member.py", line 33, in <module>
    import discord.abc
  File "C:\Users\eddis\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\abc.py", line 59, in <module>
    from .voice_client import VoiceClient, VoiceProtocol
  File "C:\Users\eddis\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\voice_client.py", line 35, in <module>
    from .player import AudioPlayer, AudioSource
  File "C:\Users\eddis\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\player.py", line 29, in <module>
    import audioop
ModuleNotFoundError: No module named 'audioop'
```

what am i doing wrong?

**Comment by Echoshard** [comment]
Is this on startup or on running it and what did you ask it?

**Comment by tetrdd** [comment]
see this pull request:
https://github.com/Echoshard/Gemini_Discordbot/pull/18
