### ISSUE TITLE
not straight forward install on ubuntu server

### ISSUE THREAD

**Issue by skullcrushercmd** [Echoshard/Gemini_Discordbot#7]
not very familiar with linux so not sure if I would need to create it in an virtual environment or what but here's the error along with other

root@nyvpn:/discord/gemini# pip install -U -r requirements.txt
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

**Comment by skullcrushercmd** [comment]
im trying to install on ubuntu server 23.10

**Comment by skullcrushercmd** [comment]
got past it by doin break system priv but 

oot@nyvpn:/discord/gemini# python3 GeminiDiscordBot.py
Traceback (most recent call last):
  File "/discord/gemini/GeminiDiscordBot.py", line 16, in <module>
    MAX_HISTORY = int(os.getenv("MAX_HISTORY"))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by skullcrushercmd** [comment]
i think the issue is simply bc you didn't link the .env file in with it or something with .env dissapearing in ubuntu when I use ls but it is there.

**Comment by skullcrushercmd** [comment]
the problem is with the packages :/
discord py for ubuntu don't like it bc of the error before with external environment

**Comment by skullcrushercmd** [comment]
tried to do it in a virtual environment and same issue pretty much

(discord) root@nyvpn:~/.venvs/Gemini_Discordbot# sudo python3 GeminiDiscordBot.py
2023-12-24 20:47:04 WARNING  discord.ext.commands.bot Privileged message content intent is missing, commands may not work as expected.
2023-12-24 20:47:04 INFO     discord.client logging in using static token
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/http.py", line 803, in static_login
    data = await self.request(Route('GET', '/users/@me'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/http.py", line 745, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.venvs/Gemini_Discordbot/GeminiDiscordBot.py", line 176, in <module>
    bot.run(DISCORD_BOT_TOKEN)
  File "/usr/local/lib/python3.11/dist-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/client.py", line 849, in runner
    await self.start(token, reconnect=reconnect)
  File "/usr/local/lib/python3.11/dist-packages/discord/client.py", line 777, in start
    await self.login(token)
  File "/usr/local/lib/python3.11/dist-packages/discord/client.py", line 612, in login
    data = await self.http.static_login(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/http.py", line 807, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.

**Comment by Echoshard** [comment]
I don't actually know what's going on I use windows servers for all my stuff. You can just set them in a separate python script.  like it was originally.

botConfig.py
